# Generated by Django 5.2.7 on 2026-03-15 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="商品番号"
                    ),
                ),
                ("item_name", models.CharField(max_length=50, verbose_name="商品名")),
                ("unit_price", models.IntegerField(verbose_name="単価")),
                ("inventory_quantity", models.IntegerField(verbose_name="在庫数")),
                ("description", models.TextField(verbose_name="説明文")),
                (
                    "image1",
                    models.ImageField(
                        upload_to="item_images", verbose_name="イメージ1"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
        ),
    ]
